"""your message

Revision ID: 64335386f768
Revises: 
Create Date: 2024-04-10 11:42:30.477207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64335386f768'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
