"""your message

Revision ID: b42b75e98ea0
Revises: 64335386f768
Create Date: 2024-04-10 11:59:51.615380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42b75e98ea0'
down_revision = '64335386f768'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
